version: '3.1'

services:
  probable-octo-chainsaw-api:
    image: dotronglong/faker:stable
    volumes:
      - ./back-end/mocks:/app/mocks
    ports:
      - "3030:3030"

  frontend_docker:
    image: node:alpine
    container_name: frontend_docker
    entrypoint: /bin/sh -c "npm install && npm run dev"
    ports:
      - 8080:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./front-end
        target: /srv/app
    tty: true
